apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-jenkins-deployment
  namespace: jenkin
  labels:
    app: springboot-jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-jenkins
  template:
    metadata:
      labels:
        app: springboot-jenkins
    spec:
      containers:
      - name: springboot-jenkins
        image: vinaypavan022/vinay:j1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://root:rootpassword@mongodb-service.mongodb-namespace.svc.cluster.local:27017/mydatabase?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-jenkins-service
  namespace: jenkin
spec:
  selector:
    app: springboot-jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-jenkins-ingress
  namespace: jenkin
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: springboot-jenkins.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: springboot-jenkins-service
            port:
              number: 8080
