image:
  repository: mongo
  tag: "6.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

mongodb:
  rootUser: root
  rootPassword: rootpassword
  database: mydatabase

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: mongodb.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

